# Generated by Django 5.0.3 on 2024-03-23 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('231b0d31-8e0e-4e62-9796-e1fb2f5f7b48'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
